package com.evgeny.app.jojoengrish.api;

public abstract class Files {
    public static String YARE_YARE_DAZE = "Yare yare daze";
    public static String WRY_SCARED = "Dio WRY (scared)";
    public static String WRY_ANGRY = "Dio WRY (angry)";
    public static String WRY_QUIET = "Dio wry (quiet)";
    public static String BITE_THE_DUST = "Bite the dust";
    public static String ROADROLLER = "Road roller da!";
    public static String ZAWARUDO = "Za warudo";
    public static String MUDA_MUDA = "Muda muda";
    public static String MUDA_MUDA_FIGHT = "Muda muda (agressive)";
    public static String STAND_POWER = "Stando powah";
    public static String KONO_DIO_DA = "Kono Dio da";
    public static String JOTARO_UNDERSTAND = "Do u understand?(Jotaro)";
    public static String UNDERSTAND = "Do u understand?";
    public static String SPEEDWAGON = "SpeedwagOOOn";
    public static String VERY_NICE = "Very nice";
    public static String DIOOOO = "Diooooo";
    public static String OH_MY_GOD = "Oh my god";
    public static String YES_OH_MY_GOD = "Yes yes, oh my god";
    public static String OH_NO = "Oh no";
    public static String HOLY_SHIT = "Holy shit";
    public static String SON_OF_A_BITCH = "Son of a bitch";
    public static String HEY_BABY = "Hey baby";
    public static String YOU_FOOL = "You utter fool!";
    public static String SHIZA = "SHIZAAA";
    public static String HELL_TO_YOU = "Hell 2 u";
    public static String BYE_JOJO = "Goodbye Jojo!";
    public static String YES_I_AM = "Yes I am!";
    public static String NICE = "Niceeee";
    public static String YES_YES = "Yes yes... YES!";
    public static String NO_NO = "No No No No";
    public static String LERO = "Lero lero";
    public static String THANK_YOU = "Thank you";
    public static String PEROLO = "Here I come";
    public static String RUN = "Run away";
    public static String ORA_ORA = "Ora ora";
    public static String BRAVO = "Bravo";
    public static String KAKOYIN = "Kakoyin death";
    public static String PRETTY = "Wow pretty";
    public static String KILL_DA_HOE = "Lets kill daho!";
    public static String GO_AHEAD = "Go ahead, mr Joestar";
    public static String ARRIVIDERCI = "Arrividerci";
    public static String GIORNO_MUDA = "Muda muda (Giorno)";
    public static String GIORNO_DREAM = "I have a dream";
    public static String STICKY_FINGERS = "Sticky fingers";
    public static String FAKE_PHONE = "Phone call";
    public static String SONOCHIDO = "Sono Chi no Sadame";

}
