package com.evgeny.app.jojoengrish.api;

import com.evgeny.app.jojoengrish.api.exceptions.NotFoundException;

public abstract class TagsTableFeeder {
    public static final String TABLE_NAME = "tags";
    public static final String KEY_ID = "ID";
    public static final String KEY_TAG = "tag";

    public static String makeContract() {
        return "CREATE TABLE IF NOT EXISTS " + TABLE_NAME + " ("
                + KEY_TAG + " VARCHAR(255), "
                + KEY_ID + " INTEGER ,"
                + "FOREIGN KEY (" + KEY_ID + ") REFERENCES "
                + SoundsTableFeeder.TABLE_NAME + " (" + SoundsTableFeeder.KEY_ID + ")"
                + ");";
    }

    public static void feed(DbHelper db) throws NotFoundException {
        int id = db.getSoundId(Files.YARE_YARE_DAZE);
        db.postTag(id, "jotaro");
        db.postTag(id, "kujo");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "yare");
        db.postTag(id, "daze");
        db.postTag(id, "good");
        db.postTag(id, "grief");

        id = db.getSoundId(Files.WRY_SCARED);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "wryyyyyyy");
        db.postTag(id, "speedwagon");
        db.postTag(id, "nazi");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        db.postTag(id, "vampire");
        db.postTag(id, "noise");
        db.postTag(id, "loudly");
        db.postTag(id, "fight");
        db.postTag(id, "scared");
        db.postTag(id, "confused");
        id = db.getSoundId(Files.WRY_ANGRY);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "wryyyyyyy");
        db.postTag(id, "speedwagon");
        db.postTag(id, "nazi");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        db.postTag(id, "vampire");
        db.postTag(id, "noise");
        db.postTag(id, "loudly");
        db.postTag(id, "fight");
        db.postTag(id, "angry");
        id = db.getSoundId(Files.WRY_SCARED);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "wryyyyyyy");
        db.postTag(id, "speedwagon");
        db.postTag(id, "nazi");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        db.postTag(id, "vampire");
        db.postTag(id, "noise");
        db.postTag(id, "quietly");
        db.postTag(id, "coffin");
        db.postTag(id, "menacing");
        id = db.getSoundId(Files.BITE_THE_DUST);
        db.postTag(id, "kira");
        db.postTag(id, "yoshikage");
        db.postTag(id, "killer");
        db.postTag(id, "queen");
        db.postTag(id, "bite");
        db.postTag(id, "dust");
        db.postTag(id, "reset");
        db.postTag(id, "time");
        db.postTag(id, "dusto");
        id = db.getSoundId(Files.ROADROLLER);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "time");
        db.postTag(id, "stop");
        db.postTag(id, "road");
        db.postTag(id, "roller");
        db.postTag(id, "da");
        db.postTag(id, "fight");
        id = db.getSoundId(Files.ZAWARUDO);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "time");
        db.postTag(id, "stop");
        db.postTag(id, "the");
        db.postTag(id, "world");
        db.postTag(id, "za");
        db.postTag(id, "fight");
        db.postTag(id, "warudo");
        db.postTag(id, "stand");
        id = db.getSoundId(Files.MUDA_MUDA);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "muda");
        db.postTag(id, "knife");
        db.postTag(id, "knives");
        db.postTag(id, "fight");
        id = db.getSoundId(Files.STAND_POWER);
        db.postTag(id, "dio");
        db.postTag(id, "brando");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "the");
        db.postTag(id, "world");
        db.postTag(id, "za");
        db.postTag(id, "fight");
        db.postTag(id, "warudo");
        db.postTag(id, "stand");
        db.postTag(id, "power");
        db.postTag(id, "powah");
        id = db.getSoundId(Files.KONO_DIO_DA);
        db.postTag(id, "dio");
        db.postTag(id, "speedwagon");
        db.postTag(id, "nazi");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        db.postTag(id, "brando");
        db.postTag(id, "it");
        db.postTag(id, "was");
        db.postTag(id, "me");
        db.postTag(id, "kono");
        db.postTag(id, "da");
        id = db.getSoundId(Files.JOTARO_UNDERSTAND);
        db.postTag(id, "jotaro");
        db.postTag(id, "kujo");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "do");
        db.postTag(id, "you");
        db.postTag(id, "understand");
        id = db.getSoundId(Files.UNDERSTAND);
        db.postTag(id, "rubber");
        db.postTag(id, "soul");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        db.postTag(id, "do");
        db.postTag(id, "you");
        db.postTag(id, "understand");
        id = db.getSoundId(Files.SPEEDWAGON);
        db.postTag(id, "speedwagon");
        db.postTag(id, "nazi");
        db.postTag(id, "soldier");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        id = db.getSoundId(Files.VERY_NICE);
        db.postTag(id, "joseph");
        db.postTag(id, "joestar");
        db.postTag(id, "ceasar");
        db.postTag(id, "chan");
        db.postTag(id, "very");
        db.postTag(id, "nice");
        db.postTag(id, "nicu");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        id = db.getSoundId(Files.DIOOOO);
        db.postTag(id, "jonathan");
        db.postTag(id, "joestar");
        db.postTag(id, "emotional");
        db.postTag(id, "angry");
        db.postTag(id, "dio");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        id = db.getSoundId(Files.OH_MY_GOD);
        db.postTag(id, "joseph");
        db.postTag(id, "joestar");
        db.postTag(id, "emotional");
        db.postTag(id, "oh");
        db.postTag(id, "my");
        db.postTag(id, "god");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        id = db.getSoundId(Files.OH_NO);
        db.postTag(id, "emotional");
        db.postTag(id, "joseph");
        db.postTag(id, "no");
        db.postTag(id, "joestar");
        db.postTag(id, "oh");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        id = db.getSoundId(Files.HOLY_SHIT);
        db.postTag(id, "emotional");
        db.postTag(id, "joseph");
        db.postTag(id, "holy");
        db.postTag(id, "hor");
        db.postTag(id, "joestar");
        db.postTag(id, "shit");
        db.postTag(id, "she");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        id = db.getSoundId(Files.SON_OF_A_BITCH);
        db.postTag(id, "emotional");
        db.postTag(id, "joseph");
        db.postTag(id, "son");
        db.postTag(id, "of");
        db.postTag(id, "joestar");
        db.postTag(id, "bitch");
        db.postTag(id, "be");
        db.postTag(id, "stardust");
        db.postTag(id, "crusaders");
        id = db.getSoundId(Files.HEY_BABY);
        db.postTag(id, "zeppeli");
        db.postTag(id, "will");
        db.postTag(id, "antonio");
        db.postTag(id, "phantom");
        db.postTag(id, "blood");
        id = db.getSoundId(Files.YOU_FOOL);
        db.postTag(id, "Braka");
        db.postTag(id, "Monoga");
        db.postTag(id, "you");
        db.postTag(id, "fool");
        db.postTag(id, "german");
        db.postTag(id, "rudol");
        db.postTag(id, "von");
        db.postTag(id, "stroheim");




    }

}
